backend/src/main/java/com/pasdaven/backend/controller/UserAccountController.java, backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/model/UserAccountEntity.java, backend/src/main/java/com/pasdaven/backend/model/UserEntity.java, backend/src/main/java/com/pasdaven/backend/repo/UserAccountRepo.java, backend/src/main/java/com/pasdaven/backend/service/UserAccountService.java, backend/src/main/java/com/pasdaven/backend/service/UserService.java
Add create account method, user entity create userAccount getter and setter.
=> feat : add create account method

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/service/PostService.java
feat : add post controller and add create post method.
=> [Gcard-44] add create post method

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/model/PostEntity.java
update route and delete unused constructor parameter
=> update route and delete unused constructor parameter

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/service/PostService.java
feat : add update post and update score method.
=> [Gcard-79] add update post method

backend/src/main/java/com/pasdaven/backend/controller/PostController.java
update route and add title prop in updatePost function
=> update route and add title prop

backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/model/UserEntity.java, backend/src/main/java/com/pasdaven/backend/service/UserService.java
feat: add get user data by ID & get all.
=> [Gcard-77] add getAllUser and getUserById method.

backend/src/main/java/com/pasdaven/backend/controller/UserAccountController.java, backend/src/main/java/com/pasdaven/backend/model/UserAccountEntity.java, backend/src/main/java/com/pasdaven/backend/service/UserAccountService.java
feat: add get user account by id & get all.
=> [Gcard 83] add getAllUserAccount and getUserAccountById method 

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/service/PostService.java
=> [Gcard 69] add deletePost method

backend/src/main/java/com/pasdaven/backend/controller/BoardController.java
feat: add update board method.
=> [Gcard 85] add updateBoard method

backend/src/main/java/com/pasdaven/backend/controller/UserAccountController.java, backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/service/UserService.java
feat: add update user & user account method.
=> [Gcard 80] add updateUser and updateUserAccount method

backend/src/main/java/com/pasdaven/backend/controller/UserController.java
=> refactor: use final statement and constructor init

backend/src/main/java/com/pasdaven/backend/controller/FollowUserController.java, backend/src/main/java/com/pasdaven/backend/model/FollowUserEntity.java, backend/src/main/java/com/pasdaven/backend/service/FollowUserService.java
=> [Gcard 61] add addFollowUser method

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/repo/PostRepo.java, backend/src/main/java/com/pasdaven/backend/service/PostService.java
=> Get posts by keyword

backend/src/main/java/com/pasdaven/backend/controller/FollowBoardController.java, backend/src/main/java/com/pasdaven/backend/model/FollowBoardEntity.java, backend/src/main/java/com/pasdaven/backend/service/FollowBoardService.java
=> [Gcard 90] add FollowBoard method

backend/src/main/java/com/pasdaven/backend/controller/LikePostController.java, backend/src/main/java/com/pasdaven/backend/model/LikePostEntity.java, backend/src/main/java/com/pasdaven/backend/service/LikePostService.java
=> [Gcard 91] add likePost method

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/repo/PostRepo.java, backend/src/main/java/com/pasdaven/backend/service/PostService.java
=> Get all posts by userId

backend/src/main/java/com/pasdaven/backend/controller/LikePostController.java, backend/src/main/java/com/pasdaven/backend/service/LikePostService.java
feat: add delete like post method
=> [Gcard 95] add deleteLikePost method

backend/src/main/java/com/pasdaven/backend/controller/FollowBoardController.java, backend/src/main/java/com/pasdaven/backend/service/FollowBoardService.java
feat: add delete follow board method
=> [Gcard 93] add deleteFollowBoard method

backend/src/main/java/com/pasdaven/backend/controller/FollowUserController.java, backend/src/main/java/com/pasdaven/backend/model/FollowUserEntity.java, backend/src/main/java/com/pasdaven/backend/service/FollowUserService.java
feat: add get follow user method
=> [Gcard 87] add getAllFollowUser & getFollowUserById

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/service/PostService.java
feat: add get post by board Id
=> [Gcard 96] add getPostByBoardId method

backend/src/main/java/com/pasdaven/backend/controller/UserAccountController.java, backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/model/UserEntity.java
userEntity's userAccount does not need @JsonIgnore, only UserAccountEntity's user need
=> fix: can't create user

backend/src/main/java/com/pasdaven/backend/controller/LikePostController.java, backend/src/main/java/com/pasdaven/backend/model/LikePostEntity.java, backend/src/main/java/com/pasdaven/backend/service/LikePostService.java
feat: add get like post method
=> [Gcard 94] add getAllLikePost and getLikePostById method

backend/src/main/java/com/pasdaven/backend/controller/FollowBoardController.java, backend/src/main/java/com/pasdaven/backend/model/FollowBoardEntity.java, backend/src/main/java/com/pasdaven/backend/service/FollowBoardService.java
feat: add get follow board method
=> [Gcard 92] add getAllFollowBoard and getFollowBoardById method

backend/src/main/java/com/pasdaven/backend/controller/FollowUserController.java, backend/src/main/java/com/pasdaven/backend/service/FollowUserService.java
feat: add delete follow user method
=> [Gcard 86] add deleteFollowUser method

backend/src/main/java/com/pasdaven/backend/model/ApplicationBoardEntity.java, backend/src/main/java/com/pasdaven/backend/repo/ApplicationBoardRepo.java, backend/src/main/java/com/pasdaven/backend/service/ApplicationBoardService.java
feat: database add application board table
=> [Gcard 84] database add ApplicationBoard table

backend/src/main/java/com/pasdaven/backend/controller/ApplicationBoardController.java, backend/src/main/java/com/pasdaven/backend/service/ApplicationBoardService.java
feat: add create application board method
=> [Gcard 97] add createApplicationBoard method

backend/src/main/java/com/pasdaven/backend/controller/CommentController.java, backend/src/main/java/com/pasdaven/backend/model/CommentEntity.java, backend/src/main/java/com/pasdaven/backend/service/CommentService.java
feat: add create comment method
=> [Gcard 100] add createComment method

frontend/src/components/sidebar/SidebarRow.jsx
https://user-images.githubusercontent.com/75478661/208720544-676f08f7-424f-45ae-9440-c85b9917889e.mov
=> fix: change <Link> to <a> to do a force reload

frontend/src/Explore.jsx, frontend/src/components/post/PostPreview.jsx, frontend/src/components/search/SearchInput.jsx
New components: `PostPreview`, `SearchInput`
=> feat: add explore page

frontend/src/App.jsx, frontend/src/BoardRoutes.jsx, frontend/src/PostRoutes.jsx, frontend/src/SidebarRoutes.jsx, frontend/src/UserRoutes.jsx
Initialize react routing.
The root is define in `App.jsx`, and import each group's routes component.
=> [Gcard-107] Set up react router

backend/src/main/java/com/pasdaven/backend/controller/ApplicationBoardController.java, backend/src/main/java/com/pasdaven/backend/service/ApplicationBoardService.java
feat: add review application board method
=> [Gcard 98] add reviewApplicationBoard method

backend/src/main/java/com/pasdaven/backend/controller/CommentController.java, backend/src/main/java/com/pasdaven/backend/repo/CommentRepo.java, backend/src/main/java/com/pasdaven/backend/service/CommentService.java
feat: add get comment by post id
=> [Gcard 105] add getCommentsByPostId method

backend/src/main/java/com/pasdaven/backend/controller/FollowUserController.java, backend/src/main/java/com/pasdaven/backend/service/FollowUserService.java
feat: add get fans by user id method
=> [Gcard 109] add getFansByUserId method

backend/src/main/java/com/pasdaven/backend/controller/UserAccountController.java, backend/src/main/java/com/pasdaven/backend/controller/UserController.java
change get user in two method
1. admin get user by id
2. get user by id
=> [Gcard 110] refactor getUserById method

backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/repo/UserRepo.java, backend/src/main/java/com/pasdaven/backend/service/UserService.java
feat: add search user by name method
=> [Gcard 60] add searchUserByName method

backend/src/main/java/com/pasdaven/backend/controller/BoardController.java, backend/src/main/java/com/pasdaven/backend/repo/BoardRepo.java, backend/src/main/java/com/pasdaven/backend/service/BoardService.java
feat: add search board by board name method
=> [Gcard 103] add searchBoardByName method

frontend/src/App.jsx, frontend/src/components/user/UserInfoCard.jsx, frontend/src/pages/User.jsx, frontend/src/routes/UserRoutes.jsx
New component: `userInfoCard`
This new component can both use in post page
=> [Gcard-108] User Info page

backend/src/main/java/com/pasdaven/backend/controller/FollowUserController.java, backend/src/main/java/com/pasdaven/backend/model/FollowUserEntity.java, backend/src/main/java/com/pasdaven/backend/model/FollowUserFollowerData.java
feat: get followed user data, get followed user follower count & followed count.
**follower count: this user have been followed by how many user.
followed count: this user follow how many user.**
=> Edit get follow user by token method

backend/src/main/java/com/pasdaven/backend/controller/PostController.java
feat: add check user whether like post or not
=> [Gcard 124] add checkUserLikePostByToken method

backend/src/main/java/com/pasdaven/backend/controller/BoardController.java
feat: add apiUrl in updateBoard method
=> update board controller

backend/src/main/java/com/pasdaven/backend/model/ApplicationBoardEntity.java, backend/src/main/java/com/pasdaven/backend/model/BoardEntity.java, backend/src/main/java/com/pasdaven/backend/model/CommentEntity.java, backend/src/main/java/com/pasdaven/backend/model/PostEntity.java, backend/src/main/java/com/pasdaven/backend/model/UserEntity.java
refactor: change database varchar length
=> [Gcard 116] refactor database entity string length

backend/pom.xml, backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/controller/UserAccountController.java, backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/repo/CommentRepo.java, backend/src/main/java/com/pasdaven/backend/repo/PostRepo.java, backend/src/main/java/com/pasdaven/backend/service/ApplicationBoardService.java, backend/src/main/java/com/pasdaven/backend/service/CommentService.java, backend/src/main/java/com/pasdaven/backend/service/FileSystemService.java, backend/src/main/java/com/pasdaven/backend/service/FollowBoardService.java, backend/src/main/java/com/pasdaven/backend/service/FollowUserService.java, backend/src/main/java/com/pasdaven/backend/service/LikePostService.java, backend/src/main/java/com/pasdaven/backend/service/PostService.java, backend/src/main/java/com/pasdaven/backend/service/UserAccountService.java, backend/src/main/java/com/pasdaven/backend/service/UserService.java, backend/src/test/java/com/pasdaven/backend/controller/ApplicationBoardControllerTest.java, backend/src/test/java/com/pasdaven/backend/controller/CommentControllerTest.java, backend/src/test/java/com/pasdaven/backend/controller/InitSeedsTest.java, backend/src/test/java/com/pasdaven/backend/controller/PostControllerTest.java, backend/src/test/java/com/pasdaven/backend/controller/UserAccountControllerTest.java, backend/src/test/java/com/pasdaven/backend/controller/UserControllerTest.java, backend/src/test/resources/seeds/application_boards.json, backend/src/test/resources/seeds/boards.json, backend/src/test/resources/seeds/comments.json, backend/src/test/resources/seeds/posts.json, backend/src/test/resources/seeds/users.json
Co-authored-by: David Ho <davidho0403@gmail.com>
=> Merge test to codecov branch

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/model/PostWithFollowUserData.java
feat: getPostByPostId also return follow user data
=> Improve getPostByPostId method

backend/src/main/java/com/pasdaven/backend/repo/CommentRepo.java, backend/src/main/java/com/pasdaven/backend/service/CommentService.java
=> get comment by desc

backend/src/main/java/com/pasdaven/backend/controller/BoardController.java, backend/src/main/java/com/pasdaven/backend/repo/FollowBoardRepo.java, backend/src/main/java/com/pasdaven/backend/repo/PostRepo.java, backend/src/main/java/com/pasdaven/backend/service/FollowBoardService.java, backend/src/main/java/com/pasdaven/backend/service/PostService.java
=> fix delete Board method

backend/src/main/java/com/pasdaven/backend/controller/PostController.java, backend/src/main/java/com/pasdaven/backend/model/PostEntity.java, backend/src/test/java/com/pasdaven/backend/controller/PostControllerTest.java, backend/src/test/resources/seeds/posts.json
update PostEntity with delete score prop
=> update PostEntity with delete score prop

backend/src/main/java/com/pasdaven/backend/controller/FollowUserController.java
=> feat: add check follow user method

frontend/src/components/price/Price.jsx, frontend/src/components/price/PriceItem.jsx
=> [Gcard-147] Price component connect to price api

backend/src/main/java/com/pasdaven/backend/controller/ApplicationBoardController.java, backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/repo/ApplicationBoardRepo.java, backend/src/main/java/com/pasdaven/backend/service/ApplicationBoardService.java, frontend/src/App.jsx, frontend/src/components/board/ReviewBoardItem.jsx, frontend/src/components/user/UserNavCard.jsx, frontend/src/pages/RequestBoard.jsx, frontend/src/pages/ReviewBoard.jsx
- Add `/requestBoard` route for normal user
- Add `/reviewBoard` route for admin user
- Add `UserController::checkIsAdmin()` to check a user is an admin or not
- Add `ApplicationBoardController::getPendingApplicationBoard()` to get the pending state's application board
=> [Gcard-57] Request, Review board page

backend/src/main/java/com/pasdaven/backend/controller/ApplicationBoardController.java, backend/src/main/java/com/pasdaven/backend/model/ApplicationBoardEntity.java
feat: application board table add apiUrl attribute
=> After approve application board, create new board in board table

backend/src/main/java/com/pasdaven/backend/controller/UserController.java, backend/src/main/java/com/pasdaven/backend/model/UserWithFollowUserData.java
add following count and fans count number.
=> UserController searchUserByName method add return value
